version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment: # cf. commentaries under videos
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/yt_larry_scott
      - bundler_gems:/usr/local/bundle/
    env_file:
      - '.env'
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundler_gems:
  postgres:
