version: '3'
services:
  db:
    image: postgres:12.1
    volumes:
      - postgres:/var/lib/postgresql/data
    environment: # cf. commentaries under videos
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: ./rails/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 'ssl://0.0.0.0:3000?key=config/ssl/localhost.key&cert=config/ssl/localhost.crt'"
    volumes:
      - ./rails/srcs:/ft_transcendence
      - bundler_gems:/usr/local/bundle/
    env_file:
      - '.env'
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundler_gems:
  postgres:
