# Add configuration values here, as shown below.
#
oauth_grant_type: "authorization_code"
oauth_client_id: "235a071025e8e19cdd302e0cff45e29c2b7c2a8b1fd37bc7cdbf4e2edc452729"
oauth_client_secret: "bd247fc761561f68598d981c4c151e43905690f9a8f99039631e5a6b1098a2dc"
oauth_redirect_uri: "http://localhost:3000/sessions/oauth"
oauth_state: "a_very_long_random_string_witchmust_be_unguessable"

# 1:CLEAN=1 / 2:INFO=1+2 / 3:DEBUG=1+2+3
logs_filter_sessions_controller: "3"
